apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: toovyqf4p-nodejs 
  janus-idp.io/tekton: toovyqf4p-nodejs
  backstage.io/kubernetes-id: toovyqf4p-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: toovyqf4p-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml